<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BreedSeeder extends Seeder
{
    private static array $breeds = [
        // AKC Sporting
        'American Water Spaniel',
        'Barbet',
        'Boykin Spaniel',
        'Brittany',
        'Chesapeake Bay Retriever',
        'Clumber Spaniel',
        'Cocker Spaniel',
        'Curly-Coated Retriever',
        'English Cocker Spaniel',
        'English Setter',
        'English Springer Spaniel',
        'Field Spaniel',
        'Flat-Coated Retriever',
        'German Shorthaired Pointer',
        'German Wirehaired Pointer',
        'Golden Retriever',
        'Gordon Setter',
        'Irish Red and White Setter',
        'Irish Setter',
        'Irish Water Spaniel',
        'Labrador Retriever',
        'Lagotto Romagnolo',
        'Nederlandse Kooikerhondje',
        'Nova Scotia Duck Tolling Retriever',
        'Pointer',
        'Portuguese Water Dog',
        'Spinone Italiano',
        'Sussex Spaniel',
        'Vizsla',
        'Weimaraner',
        'Welsh Springer Spaniel',
        'Wirehaired Pointing Griffon',
        'Wirehaired Vizsla',

        // AKC Hound
        'Afghan Hound',
        'American English Coonhound',
        'American Foxhound',
        'Basenji',
        'Basset Hound',
        'Beagle',
        'Black and Tan Coonhound',
        'Bloodhound',
        'Bluetick Coonhound',
        'Borzoi',
        "Cirneco dell'Etna",
        'Dachshund',
        'English Foxhound',
        'Grand Basset Griffon Vendéen',
        'Greyhound',
        'Harrier',
        'Ibizan Hound',
        'Irish Wolfhound',
        'Norwegian Elkhound',
        'Otterhound',
        'Petit Basset Griffon Vendéen',
        'Pharaoh Hound',
        'Plott Hound',
        'Portuguese Podengo Pequeno',
        'Redbone Coonhound',
        'Rhodesian Ridgeback',
        'Saluki',
        'Scottish Deerhound',
        'Sloughi',
        'Treeing Walker Coonhound',
        'Whippet',

        // AKC Working
        'Akita',
        'Alaskan Malamute',
        'Anatolian Shepherd Dog',
        'Bernese Mountain Dog',
        'Black Russian Terrier',
        'Boerboel',
        'Boxer',
        'Bullmastiff',
        'Cane Corso',
        'Chinook',
        'Dogo Argentino',
        'Doberman Pinscher',
        'Dogue de Bordeaux',
        'German Pinscher',
        'Giant Schnauzer',
        'Great Dane',
        'Great Pyrenees',
        'Greater Swiss Mountain Dog',
        'Komondor',
        'Kuvasz',
        'Leonberger',
        'Mastiff',
        'Neapolitan Mastiff',
        'Newfoundland',
        'Rottweiler',
        'Saint Bernard',
        'Samoyed',
        'Siberian Husky',
        'Standard Schnauzer',
        'Tibetan Mastiff',
        'Tornjak',

        // AKC Terrier
        'Airedale Terrier',
        'American Hairless Terrier',
        'American Staffordshire Terrier',
        'Australian Terrier',
        'Bedlington Terrier',
        'Border Terrier',
        'Bull Terrier',
        'Cairn Terrier',
        'Cesky Terrier',
        'Dandie Dinmont Terrier',
        'Glen of Imaal Terrier',
        'Irish Terrier',
        'Jack Russell Terrier',
        'Kerry Blue Terrier',
        'Lakeland Terrier',
        'Manchester Terrier',
        'Miniature Bull Terrier',
        'Miniature Schnauzer',
        'Norfolk Terrier',
        'Norwich Terrier',
        'Parson Russell Terrier',
        'Russell Terrier',
        'Scottish Terrier',
        'Sealyham Terrier',
        'Skye Terrier',
        'Smooth Fox Terrier',
        'Soft Coated Wheaten Terrier',
        'Staffordshire Bull Terrier',
        'Welsh Terrier',
        'West Highland White Terrier',
        'Wire Fox Terrier',
        'Yorkshire Terrier',

        // AKC Toy
        'Affenpinscher',
        'Biewer Terrier',
        'Brussels Griffon',
        'Cavalier King Charles Spaniel',
        'Chihuahua',
        'Chinese Crested',
        'English Toy Spaniel',
        'Havanese',
        'Italian Greyhound',
        'Japanese Chin',
        'Maltese',
        'Miniature Pinscher',
        'Papillon',
        'Pekingese',
        'Pomeranian',
        'Pug',
        'Russian Toy',
        'Shih Tzu',
        'Silky Terrier',
        'Toy Fox Terrier',
        'Toy Manchester Terrier',
        'Toy Poodle',

        // AKC Non-Sporting
        'American Eskimo Dog',
        'Bichon Frise',
        'Boston Terrier',
        'Bulldog',
        'Chinese Shar-Pei',
        'Chow Chow',
        'Coton de Tulear',
        'Dalmatian',
        'Finnish Spitz',
        'French Bulldog',
        'Keeshond',
        'Lhasa Apso',
        'Löwchen',
        'Miniature Poodle',
        'Norwegian Lundehund',
        'Poodle',
        'Schipperke',
        'Shiba Inu',
        'Tibetan Spaniel',
        'Tibetan Terrier',
        'Xoloitzcuintli',

        // AKC Herding
        'Australian Cattle Dog',
        'Australian Shepherd',
        'Bearded Collie',
        'Beauceron',
        'Belgian Laekenois',
        'Belgian Malinois',
        'Belgian Sheepdog',
        'Belgian Tervuren',
        'Bergamasco Sheepdog',
        'Berger Picard',
        'Border Collie',
        'Bouvier des Flandres',
        'Briard',
        'Canaan Dog',
        'Cardigan Welsh Corgi',
        'Collie',
        'Entlebucher Mountain Dog',
        'Finnish Lapphund',
        'German Shepherd Dog',
        'Icelandic Sheepdog',
        'Miniature American Shepherd',
        'Norwegian Buhund',
        'Old English Sheepdog',
        'Pembroke Welsh Corgi',
        'Polish Lowland Sheepdog',
        'Puli',
        'Pumi',
        'Pyrenean Shepherd',
        'Shetland Sheepdog',
        'Spanish Water Dog',
        'Swedish Vallhund',

        // UKC / Other Registry
        'Alapaha Blue Blood Bulldog',
        'American Bulldog',
        'American Pit Bull Terrier',
        'Black Mouth Cur',
        'Blue Lacy',
        'Carolina Dog',
        'Catahoula Leopard Dog',
        'Feist',
        'Jindo',
        'Mountain Cur',
        'Mountain View Cur',
        'Perro de Presa Canario',
        'Rat Terrier',
        'Teddy Roosevelt Terrier',
        'Treeing Tennessee Brindle',

        // Mixed / Designer Breeds
        'Aussiedoodle',
        'Bernedoodle',
        'Cavapoo',
        'Chocolate Labrador',
        'Cockapoo',
        'Dachshund Mix',
        'Goldendoodle',
        'Labradoodle',
        'Labrador Mix',
        'Maltipoo',
        'Mixed Breed',
        'Morkie',
        'Pit Bull Terrier',
        'Pomsky',
        'Puggle',
        'Schnauzer Mix',
        'Schnoodle',
        'Sheepadoodle',
        'Shorkie',
        'Yorkipoo',
    ];

    public function run(): void
    {
        $now = now();
        $rows = array_map(fn (string $name) => [
            'name' => $name,
            'created_at' => $now,
            'updated_at' => $now,
        ], self::$breeds);

        DB::table('breeds')->upsert($rows, ['name'], ['updated_at']);
    }
}
